# Generated by Django 3.0.3 on 2020-04-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Known_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_x', models.CharField(max_length=50)),
                ('drug_y', models.CharField(max_length=50)),
                ('relation_value', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_x', models.CharField(max_length=50)),
                ('drug_y', models.CharField(max_length=50)),
                ('relation_value', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
    ]
